<a href="https://colab.research.google.com/github/toan722003/Machine_Learning/blob/master/Lab1_21130568_NguyenNhuToan.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Task 1. Python Programming**

In [61]:
import numpy as np

In [ ]:
# Task 1.1
# Input an integer number n
n = input("Input your number: ")

Input your number: 12


In [ ]:
# Task 1.1
# Input n integer numbers x1, x2,..., xn and append them into a list L.
L = []
i = 0
while i < 10:
  n = input("Input your number: ")
  L.append(int(n))
  i += 1
print(L)

Input your number: 12
Input your number: -5
Input your number: 48
Input your number: -9
Input your number: 89
Input your number: -56
Input your number: 42
Input your number: 53
Input your number: -7
Input your number: -32
[12, -5, 48, -9, 89, -56, 42, 53, -7, -32]


In [ ]:
# Task 1.1
# Compute the sum of elements in L
print(f"{np.sum(L)}")

135


In [ ]:
# from posixpath import lexistsreg
# Task 1.1
# Sort the list L in ascending order
print(f"{np.sort(L)}")

[-56 -32  -9  -7  -5  12  42  48  53  89]


In [ ]:
# Task1.1
# Show how many positive and negative numbers are in the list L.
positive = 0
negative = 0
for i in L:
  if i < 0:
    negative +=1
  else:
    positive +=1
print(f"Positive: {positive}")
print(f"Negative: {negative}")

Positive: 5
Negative: 5


In [ ]:
# Task 1.2
# Implement a Python function to compute S(n) as follows:
# S(n)=1+1.2+1.2.3+…+1.2.3…n, n>0
sum = 0
def sumN(n):
    if(n <= 0):
       return sum
    tich = 1
    for i in range(n):
      tich = tich * (i+1)
    n -= 1
    return sum + tich + sumN(n)
print(f"Sum is: {sumN(5)}")

Sum is: 153


In [7]:
# Task 1.3
class Post:
  def __init__(self,content,subject,likes):
    self.__content = content
    self.__subject = subject
    self.__likes = likes

  def get_content(self):
    return self.__content

  def get_subject(self):
    return self.__subject

  def get_likes(self):
    return self.__likes

In [30]:
class Account:
  def __init__(self,name,email,country):
    self.__name = name
    self.__email = email
    self.__country = country
    self.__friends = list()
    self.__posts = list()

  def get_name(self):
    return self.__name

  def get_email(self):
    return self.__email

  def get_country(self):
    return self.__country

  def add_friend(self,friend):
    self.__friends.append(friend)

  def add_post(self,post):
    self.__posts.append(post)

  def get_posts(self):
    return self.__posts

  def getMaxLikePostByFriend(self):
    max = 0
    account = self
    for acc in self.__friends:
      if(len(acc.__posts) > 0):
        for post in acc.__posts:
          if(post.get_likes() > max):
             account = acc
    return account

  def __str__(self):
    return f"Name: {self.__name},Email: {self.__email},Country: {self.__country}"

In [55]:
class AccountManager:
  def __init__(self):
    self.__accounts = list()

  def add_account(self,account):
    self.__accounts.append(account)

  def groupAccountsByPostLike(self):
    trueMap = dict(true = list(),false = list())
    for account in self.__accounts:
      if(len(account.get_posts()) > 10):
        trueMap["true"].append(account)
      else:
        trueMap["false"].append(account)
    return trueMap

  def filterAccounts(self,country):
    setAccount = filter(lambda acc: acc.get_country == country,self.__accounts)
    return setAccount

In [52]:
# Test
post1 = Post("1","A",10)
post2 = Post("2","B",4)
post3 = Post("3","C",108)
post4 = Post("4","E",109)
post5 = Post("5","F",3)
post6 = Post("6","F",1)
post7 = Post("7","G",0)
post8 = Post("8","H",107)

acc1 = Account("NNT","abc@gmail.com","Vn")
acc2 = Account("NNB","abcde@gmail.com","Vn")
acc3 = Account("NTTA","abcdef@gmail.com","Vn")
acc1.add_post(post1)
acc1.add_post(post2)
acc2.add_post(post5)
acc2.add_post(post8)
acc2.add_post(post4)
acc3.add_post(post3)
acc3.add_post(post6)
acc3.add_post(post7)

acc1.add_friend(acc2)
acc1.add_friend(acc3)

accManage = AccountManager()
accManage.add_account(acc1)
accManage.add_account(acc2)
accManage.add_account(acc3)

In [43]:
accTest1 = acc1.getMaxLikePostByFriend()
print(accTest1)

Name: NTTA,Email: abcdef@gmail.com,Country: Vn


In [49]:
mapAcc = accManage.groupAccountsByPostLike()

for key,value in mapAcc.items():
  print(key)
  if(len(value) == 0):
    print("Rỗng")
  else:
    for v in value:
      print(v)

true
Rỗng
false
Name: NNT,Email: abc@gmail.com,Country: Vn
Name: NNB,Email: abcde@gmail.com,Country: Vn
Name: NTTA,Email: abcdef@gmail.com,Country: Vn


In [58]:
setAcc = accManage.filterAccounts("Vnn")
print(setAcc)
setAcc = accManage.filterAccounts("Vn")
print(setAcc)

set()
set()


**Task 2. NumPy**

In [63]:
# Task 2.1
def createNumber(start,end):
  array = np.arange(start,end,1)
  print(array)
  print(np.sort(array)[::-1])
createNumber(10,25)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [72]:
# Task 2.2
origin_array = [1, 2, 3, 4]
repeat_array = []
for i in range(4):
  repeat_array.append(origin_array.copy())
print(repeat_array)


[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]


In [81]:
# Task 2.3
def changeArrayByNumberSpecifice(num):
  arr = [[ 0.42, 0.48, 0.32],[ 0.74 ,0.58, 0.38],[ 0.51, 0.34, 0.15 ]]
  og_array = np.array(arr)
  for i in range(len(og_array)):
    for j in range(len(og_array[i])):
      if(og_array[i,j] > 0.5):
        og_array[i,j] = num
  return og_array
  # print(og_array[0,0])
print(changeArrayByNumberSpecifice(0.5))


[[0.42 0.48 0.32]
 [0.5  0.5  0.38]
 [0.5  0.34 0.15]]
